#!/bin/bash

DIR=tests

# compile tests
g++ $DIR/tests.cpp math.cpp -o $DIR/a.out -DPRIME_GENERATION

# remove files from previous executions
rm -rf $DIR/figure.png
rm -rf $DIR/output
rm -rf $DIR/table.txt

# get the data and store them in temporary files
for ((i=0; i<100; i++)); do
		./$DIR/a.out > $DIR/output
		sleep 1 
		printf "$i $(cat $DIR/output | sort -u | wc -l)\n" >> $DIR/table.txt
done

# delete temporary files
rm -rf $DIR/output
rm -rf $DIR/a.out

# (OPTIONAL): output the data in tabular form
# cat $DIR/table.txt

# plot the results
gnuplot <<- EOF
	set title "Distribution of rand(): prime number generation"
	set xlabel "Repetitions"
	set ylabel "#different primes"
	set font "Verdana 12"
	set terminal png
	set output 'tests/figure.png'
	f(x) = a*x + b
	fit f(x) 'tests/table.txt' using 1:2 via a,b
	plot[0:50][80:110] 'tests/table.txt' using 1:2 title "primes generated" with points , f(x) title 'model fit'
EOF

# show the results
xdg-open $DIR/figure.png

# remove the dataset and the log file generated by gnuplot
rm -rf $DIR/table.txt
rm -rf fit.log
